### ISSUE TITLE
path's format is not supported

### ISSUE THREAD

**Issue by d3fr0st** [jacob-keller/L0G-101086#18]
```
New-Item : The given path's format is not supported.
At C:\Users\Laurent\Documents\Guild Wars 2\addons\arcdps\upload-logs.ps1:144 char:5
+     New-Item -ItemType Directory -Path $dir
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-Item], NotSupportedException
    + FullyQualifiedErrorId : System.NotSupportedException,Microsoft.PowerShell.Commands.NewItemCommand
```

Has been happening trying to upgrade to any version past 2.1.0

**Comment by jacob-keller** [comment]
what is the value in the config file for extra_upload_data, and is it a valid directory?

I can probably add more verbose logging here to make it more obvious what is broken.

**Comment by d3fr0st** [comment]
It's the default value, same value works fine in 2.1.0

"%UserProfile%\\Documents\\Guild Wars 2\\addons\\arcdps\\arcdps.uploadextras"

**Comment by jacob-keller** [comment]
I just added a bit more exception handling logic to this. Can you try the latest commit on master? Also, when you do, see if there's any relevant data in upload_log.txt

**Comment by d3fr0st** [comment]
Powershell
```
PS C:\Users\Laurent\Documents\Guild Wars 2\addons\arcdps> C:\Users\Laurent\Documents\Guild Wars 2\addons\arcdps\upload-logs.ps1
Write-Exception : 
MyCommand             : New-Item
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 152
OffsetInLine          : 9
HistoryId             : 5
ScriptName            : C:\Users\Laurent\Documents\Guild Wars 2\addons\arcdps\upload-logs.ps1
Line                  :         New-Item -ItemType Directory -Path $dir
                        
PositionMessage       : At C:\Users\Laurent\Documents\Guild Wars 2\addons\arcdps\upload-logs.ps1:152 char:9
                        +         New-Item -ItemType Directory -Path $dir
                        +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PSScriptRoot          : C:\Users\Laurent\Documents\Guild Wars 2\addons\arcdps
PSCommandPath         : C:\Users\Laurent\Documents\Guild Wars 2\addons\arcdps\upload-logs.ps1
InvocationName        : New-Item
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition : 
Data                  : {}
HelpLink              : 
HResult               : -2146233067
InnerException        : 
Message               : The given path's format is not supported.
Source                : mscorlib
StackTrace            :    at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
                           at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
                           at Microsoft.PowerShell.Commands.FileSystemProvider.CreateDirectory(String path, Boolean streamOutput)
                           at Microsoft.PowerShell.Commands.FileSystemProvider.NewItem(String path, String type, Object value)
                           at System.Management.Automation.SessionStateInternal.NewItemPrivate(CmdletProvider providerInstance, String path, String type, Object 
                        content, CmdletProviderContext context)
TargetSite            : Void EmulateFileIOPermissionChecks(System.String)
At C:\Users\Laurent\Documents\Guild Wars 2\addons\arcdps\upload-logs.ps1:154 char:9
+         Write-Exception $_
+         ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Exception
 
Unable to process C:\Users\Laurent\Documents\Guild Wars 2\addons\arcdps\arcdps.cbtlogs\Dhuum\20181219-211510.evtc... Press any key to exit...: ```

**Comment by d3fr0st** [comment]
upload_log.txt
```Saving ancillary data for C:\Users\Laurent\Documents\Guild Wars 2\addons\arcdps\arcdps.cbtlogs\Dhuum\20181219-211510.evtc...
Unable to create extra upload directory 'C:\Users\Laurent\Documents\Guild Wars 2\addons\arcdps\arcdps.uploadextras\C:\Users\Laurent\Documents\Guild Wars 2\addons\arcdps\arcdps.cbtlogs\Dhuum\20181219-211510.evtc'```

**Comment by jacob-keller** [comment]
nable to create extra upload directory 'C:\Users\Laurent\Documents\Guild Wars 2\addons\arcdps\arcdps.uploadextras\C:\Users\Laurent\Documents\Guild Wars 2\addons\arcdps\arcdps.cbtlogs\Dhuum\20181219-211510.evtc'```

So that line is suspicious hmm.. it looks like it's somehow trying to use the full path to the file...

Oh.. your logs aren't compresed, are they?

**Comment by d3fr0st** [comment]
They aren't, turned it off when zevtc happened and hadn't turned that back on

**Comment by d3fr0st** [comment]
```Test-Path : A parameter cannot be found that matches parameter name 'dir'.
At C:\Users\Laurent\Documents\Guild Wars 2\addons\arcdps\upload-logs.ps1:140 char:29
+         If (-not (Test-Path -dir $dir)) {
+                             ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Test-Path], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.TestPathCommand```

**Comment by jacob-keller** [comment]
Woops, typo in a separate commit. I think I just fixed that, sorry about that one. I'm going to rebase the original merge.

**Comment by jacob-keller** [comment]
Try what's on master when you get a chance, I merged the pull request.

**Comment by d3fr0st** [comment]
2.4.2 fixes the issue
